services:
  zodvalidationerror:
    image: zodvalidationerror
    build:
      context: frontend/node_modules/zod-validation-error
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "./v4/index.js"]
