services:
  zodvalidationerror:
    image: zodvalidationerror
    build:
      context: frontend/node_modules/zod-validation-error
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
