server {
  listen 80;
  server_name omega-house.online www.omega-house.online;

  root /var/www/omega-house.online/dist;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }
}
